---
archs:
  - ppc64le:
      distro: el8
  - x86_64:
      distro:
        - el8
        - el9stream:
            runtime-requirements:
              host_distro: newer

release_branches:
  master:
    - ovirt-master
